"""The finger assignment, the barres it implies, and the movement it can see.

Stage 1 of [docs/fingering.md](../docs/fingering.md) §5: `arranger.fingers` exists and is
inert, so nothing in this file may assert a change in any existing behaviour - every
assertion is about the module's own answer, on a shape built by hand or generated by the
engine for the purpose. `TestTheModuleIsInert` below is what holds that claim to account.

What is tested is that document's §2.1-2.2: the constraints that follow from four fingers
(one string one finger; one finger one fret; same fret means one finger; a barre blocks
reach below it) and the conventions adopted for v1 (monotone; classical position as the
score; the index's barre). What is **not** tested is anything §2.3 leaves to measurement -
finger-pair asymmetry, position-dependent reach - and the two known limitations the module
names in its own docstrings have their own tests rather than being left unsaid.
"""

from __future__ import annotations

import ast
import unittest
from functools import lru_cache
from pathlib import Path
from typing import List, Tuple

from musthe import Note

import arranger
from arranger import (
    GRIP_PREFERENCE,
    MELODY_STRING_CHOICES_FULL,
    ChordParser,
    VoiceLeadingEngine,
    Voicing,
)
from arranger.fingers import (
    FINGERS,
    INDEX,
    MIDDLE,
    NO_FINGER,
    PINKY,
    RING,
    Fingering,
    assign_fingers,
    finger_movement,
)
from tests.support import make_voicing, note_name

# The register the library voices, as docs/engine.md states it.
MELODY_LOW = Note("G3").midi_note()
MELODY_HIGH = Note("Bb5").midi_note()


@lru_cache(maxsize=1)
def corpus() -> Tuple[Voicing, ...]:
    """Every shape the engine generates on a C root: every quality, every melody, every grip.

    Rooted on one pitch class rather than four because it is the *fret numbers* the
    assignment reads, and transposing the whole corpus a fourth moves every shape without
    changing one finger relationship. Every semitone of the register is used rather than only
    the chord tones, so the quality-only fallback shapes - the wide, oddly-fingered ones the
    drop-2 tables cannot reach - are in the corpus too.

    Measured at 8,789 shapes in 1.6 s, so it is built once and shared by the sweeps below.
    """
    engine = VoiceLeadingEngine()
    shapes: List[Voicing] = []
    for quality in sorted(ChordParser.CHORD_TONES_FROM_ROOT):
        chord_name = "C" + quality
        for midi in range(MELODY_LOW, MELODY_HIGH + 1):
            shapes.extend(
                engine.get_all_grip_voicings(
                    Note(note_name(midi)),
                    quality,
                    chord_name=chord_name,
                    top_strings=MELODY_STRING_CHOICES_FULL,
                    grips=GRIP_PREFERENCE,
                )
            )
    return tuple(shapes)


def fingering_for(frets: List[int]) -> Fingering:
    """The assignment for a hand-built shape, narrowed to the non-optional type.

    A bare `assert` rather than `assertIsNotNone`, because pyright narrows through the
    first and not through the second - the narrowing trap `AGENTS.md` records. One function
    keeps it in one place instead of at every call site.
    """
    fingering = assign_fingers(make_voicing(frets))
    assert fingering is not None, f"{frets} needs more than four fingers"
    return fingering


class TestTheAssignment(unittest.TestCase):
    """§3 steps 1-4: group by fret, assign monotonically, score, tie-break."""

    def test_a_shared_fret_is_held_by_one_finger(self) -> None:
        """`x-x-6-7-6-x` is two fingers, not three: constraint 3, and §1.1's own example.

        Fret 6 on the D and B strings is one index laid across them; the middle finger takes
        the 7 between. This is the shape that made a *per-string* movement metric wrong, so
        the assignment that makes it one finger is stated here directly.
        """
        fingering = fingering_for([-1, -1, 6, 7, 6, -1])
        self.assertEqual(
            fingering.fingers, [NO_FINGER, NO_FINGER, INDEX, MIDDLE, INDEX, NO_FINGER]
        )
        self.assertEqual(fingering.frets_by_finger, {INDEX: 6, MIDDLE: 7})
        self.assertEqual(fingering.finger_count, 2)

    def test_a_bunched_shape_sits_in_the_classical_position(self) -> None:
        """Convention 7: index f, middle f+1, ring f+2, with no finger wasted or doubled."""
        fingering = fingering_for([-1, -1, 3, 4, 5, -1])
        self.assertEqual(
            fingering.fingers, [NO_FINGER, NO_FINGER, INDEX, MIDDLE, RING, NO_FINGER]
        )
        self.assertEqual(fingering.frets_by_finger, {INDEX: 3, MIDDLE: 4, RING: 5})

    def test_a_four_fret_reach_is_index_to_pinky(self) -> None:
        """The score's spread rule: frets 3 and 7 are the index's and the pinky's.

        `_assignment_score` prefers `(INDEX, PINKY)` over `(INDEX, MIDDLE)` across a
        four-fret gap because the miss from the classical position is smaller, which is what
        "spread the chosen fingers across the span rather than bunching them" means in code.
        """
        fingering = fingering_for([-1, -1, 3, -1, 7, -1])
        self.assertEqual(
            fingering.fingers, [NO_FINGER, NO_FINGER, INDEX, NO_FINGER, PINKY, NO_FINGER]
        )

    def test_an_open_string_takes_no_finger_and_is_not_the_lowest_fret(self) -> None:
        """`x-x-0-2-3-x`: the open D sounds below the hand but is not part of it.

        Fret 0 needs no finger, and - the part worth pinning - it does not take the index
        either: the lowest *fretted* note is the 2 on the G string, so the index goes there.
        Reading fret 0 as the shape's bottom would put every finger one place too high.
        """
        fingering = fingering_for([-1, -1, 0, 2, 3, -1])
        self.assertEqual(
            fingering.fingers, [NO_FINGER, NO_FINGER, NO_FINGER, INDEX, MIDDLE, NO_FINGER]
        )
        self.assertEqual(fingering.frets_by_finger, {INDEX: 2, MIDDLE: 3})

    def test_an_all_muted_shape_uses_no_fingers(self) -> None:
        """A shape with nothing sounding is not an error: it is a rest, and costs no hand."""
        fingering = fingering_for([-1] * 6)
        self.assertEqual(fingering.fingers, [NO_FINGER] * 6)
        self.assertEqual(fingering.frets_by_finger, {})
        self.assertEqual(fingering.finger_count, 0)
        self.assertIsNone(fingering.barre_fret)
        self.assertEqual(fingering.barre_finger, NO_FINGER)

    def test_a_lower_fret_never_takes_a_higher_finger(self) -> None:
        """Convention 6: the crossing alternative is never chosen, even where it reaches less.

        `x-x-3-x-5-x` could be fingered middle at 3 and index at 5 - one fret of reach rather
        than two - and that shape is what this module refuses by construction. The assertion is
        on the choice and not on the score, because the score is an implementation of the
        convention and this is the convention.
        """
        fingering = fingering_for([-1, -1, 3, -1, 5, -1])
        self.assertEqual(
            fingering.fingers, [NO_FINGER, NO_FINGER, INDEX, NO_FINGER, RING, NO_FINGER]
        )
        self.assertLess(INDEX, RING)


class TestBarres(unittest.TestCase):
    """Constraint 3 (same fret, one finger) and convention 8 (whose job the barre is)."""

    def test_an_index_barre_is_reported_as_the_index(self) -> None:
        """`x-x-3-3-5-x`: the shared low fret takes the index, which is convention 8's rule."""
        fingering = fingering_for([-1, -1, 3, 3, 5, -1])
        self.assertEqual(
            fingering.fingers, [NO_FINGER, NO_FINGER, INDEX, INDEX, RING, NO_FINGER]
        )
        self.assertEqual(fingering.barres, {3: INDEX})
        self.assertEqual(fingering.barre_fret, 3)
        self.assertEqual(fingering.barre_finger, INDEX)

    def test_a_shared_fret_above_the_lowest_is_not_the_index(self) -> None:
        """`x-x-3-5-5-x`: the ring finger covers the pair, and the index stays below it.

        Convention 8 says barres are the index's job, and constraint 4 is why this one is not:
        a finger below a barre cannot sound, so a barre *above* a fretted note cannot be the
        index. That partial barre is the exception §2.2 item 8 records, and it falls out of
        the score rather than being special-cased.
        """
        fingering = fingering_for([-1, -1, 3, 5, 5, -1])
        self.assertEqual(
            fingering.fingers, [NO_FINGER, NO_FINGER, INDEX, RING, RING, NO_FINGER]
        )
        self.assertEqual(fingering.barres, {5: RING})
        self.assertEqual(fingering.barre_fret, 5)
        self.assertEqual(fingering.barre_finger, RING)

    def test_two_shared_frets_are_both_recorded_and_the_lowest_is_reported(self) -> None:
        """`x-x-3-3-5-5` bars two frets; `barre_fret` reports the lower of them.

        The lower one is the reported barre because it is the one that blocks reach below it
        (constraint 4), so it is what decides which fingers the others lie above. Recording
        only the first pair found would be the one-fact-two-homes mistake in reverse.
        """
        fingering = fingering_for([-1, -1, 3, 3, 5, 5])
        self.assertEqual(
            fingering.fingers, [NO_FINGER, NO_FINGER, INDEX, INDEX, RING, RING]
        )
        self.assertEqual(fingering.barres, {3: INDEX, 5: RING})
        self.assertEqual(fingering.barre_fret, 3)
        self.assertEqual(fingering.barre_finger, INDEX)

    def test_a_shape_with_no_repeated_fret_has_no_barre(self) -> None:
        """A barre is an inference from the shape, so a shape without one reports none."""
        fingering = fingering_for([-1, -1, 3, 4, 5, -1])
        self.assertEqual(fingering.barres, {})
        self.assertIsNone(fingering.barre_fret)
        self.assertEqual(fingering.barre_finger, NO_FINGER)


class TestOverTheGeneratedCorpus(unittest.TestCase):
    """The feasibility half of §3: every shape the engine generates is assignable.

    Feasibility is guaranteed in the counting sense (§2.1 constraint 2), because a generated
    shape sounds at most four strings - so these tests are about the *conventions* holding
    over the whole corpus rather than about the enumeration finding an answer at all.
    """

    def test_every_generated_shape_can_be_assigned(self) -> None:
        """Nothing in 8,789 generated shapes needs a fifth finger.

        A shape sounds two to four strings, so it has at most four distinct frets and always
        has a monotone assignment. The size of the sweep is asserted too: a corpus that
        silently came back empty would pass this test while checking nothing.
        """
        shapes = corpus()
        self.assertGreater(len(shapes), 5000)
        unassigned = [v.tab_string() for v in shapes if assign_fingers(v) is None]
        self.assertEqual(
            unassigned, [], "a generated shape needs more fingers than a hand has"
        )

    def test_no_generated_shape_frets_more_than_four_distinct_positions(self) -> None:
        """The reason the refusal is unreachable from a grip: at most four strings sound.

        This is the fact §4.3's measurement rests on - merging a walking-bass note under a
        four-note shape is the only thing in this engine that can produce a fifth fret.
        """
        offending = [
            v.tab_string()
            for v in corpus()
            if len({fret for fret in v.frets if fret >= 1}) > len(FINGERS)
        ]
        self.assertEqual(offending, [])

    def test_the_assignment_is_monotone(self) -> None:
        """Fingers ascend with frets and never double up: conventions 6 and 3, corpus-wide."""
        for v in corpus():
            fingering = assign_fingers(v)
            assert fingering is not None
            per_fret = {
                fret: finger
                for fret, finger in zip(v.frets, fingering.fingers)
                if fret >= 1
            }
            frets = sorted(per_fret)
            fingers = [per_fret[fret] for fret in frets]
            where = v.tab_string()
            self.assertEqual(fingers, sorted(fingers), where)
            self.assertEqual(len(set(fingers)), len(fingers), where)

    def test_every_fretted_string_has_a_finger_and_no_other_string_does(self) -> None:
        """Constraint 1: one finger per note, and none spent on a mute or an open string."""
        for v in corpus():
            fingering = assign_fingers(v)
            assert fingering is not None
            where = v.tab_string()
            for string_index, fret in enumerate(v.frets):
                finger = fingering.fingers[string_index]
                self.assertEqual(fret >= 1, finger != NO_FINGER, where)
                if fret >= 1:
                    self.assertEqual(fingering.fret_of(finger), fret, where)

    def test_the_melody_gets_a_finger_unless_it_is_open(self) -> None:
        """The soprano is the note being sung, so it is fingered - by a barre or otherwise.

        The one exception is an open string: G3 on the open G string is a legal melody and
        costs no finger, and this keeps that case from looking like a bug for ever after.
        """
        for v in corpus():
            fingering = assign_fingers(v)
            assert fingering is not None
            soprano = v.soprano_string()
            where = v.tab_string()
            self.assertGreaterEqual(soprano, 0, where)
            if v.frets[soprano] >= 1:
                self.assertNotEqual(fingering.fingers[soprano], NO_FINGER, where)
            else:
                self.assertEqual(fingering.fingers[soprano], NO_FINGER, where)

    def test_the_same_shape_always_assigns_the_same_way(self) -> None:
        """Determinism, which is what the tie-break exists for: tests pin tabs.

        Sampled rather than swept - a pure function of the frets cannot wobble on one shape
        and not another - but sampled across the corpus rather than over the hand-built
        shapes, so the fallback shapes are in the sample.
        """
        sample = corpus()[::13]
        self.assertGreater(len(sample), 100)
        for v in sample:
            first = assign_fingers(v)
            second = assign_fingers(v)
            assert first is not None and second is not None
            self.assertIsInstance(first, Fingering)
            self.assertEqual(first, second, v.tab_string())


class TestTheFiveFretRefusal(unittest.TestCase):
    """The one shape four fingers cannot hold, and why refusing is a value (§2.2 item 6)."""

    def test_five_distinct_frets_are_refused(self) -> None:
        """One finger holds one fret, so five distinct frets need five fingers.

        Asserted on a hand-built shape rather than a generated one, because no grip can
        produce it - the sweep above is the assertion that says no generated shape does.
        """
        self.assertIsNone(assign_fingers(make_voicing([-1, 3, 5, 6, 7, 8])))

    def test_the_refusal_is_the_merged_walking_bass_step(self) -> None:
        """§4.3: a four-note shape plus the thumb note below it is five distinct frets.

        The upper shape alone is playable; adding the thumb at fret 3 - a step below the
        shape's lowest fret, which is where a walking bass sits - makes it something the left
        hand cannot finger, because `bass.py`'s thumb is a *right-hand* pluck and the left
        hand has only four fingers. So this test is the §4.3 hook itself: counting
        `assign_fingers(step.voicing) is None` over a corpus is the measurement its §5 step 2
        asks for, and this is the shape that count is looking for.
        """
        self.assertIsNotNone(assign_fingers(make_voicing([-1, 5, 6, 7, 8, -1])))
        self.assertIsNone(assign_fingers(make_voicing([3, 5, 6, 7, 8, -1])))

    def test_five_strings_is_fine_when_two_of_them_share_a_fret(self) -> None:
        """The bound is distinct *frets*, not sounding strings, and a barre buys the fifth.

        `5-5-6-7-8-x` sounds five strings: the index bars the low E and the A at 5, leaving
        three fingers for 6, 7 and 8. Reading the refusal as "at most four strings" would call
        this shape unplayable, which is the opposite of what a player would say.
        """
        fingering = fingering_for([5, 5, 6, 7, 8, -1])
        self.assertEqual(
            fingering.fingers, [INDEX, INDEX, MIDDLE, RING, PINKY, NO_FINGER]
        )
        self.assertEqual(fingering.barres, {5: INDEX})
        self.assertEqual(fingering.finger_count, 4)


class TestFingerMovement(unittest.TestCase):
    """§3 step 5, keyed on the finger: the barre fix and the anchored leap."""

    def test_a_moving_barre_counts_once_where_the_per_string_metric_counts_twice(self) -> None:
        """§1.1's own example: `x-x-6-7-6-x` -> `x-x-7-8-7-x` moves two fingers, not three.

        The index slides the barre from 6 to 7 and the middle follows from 7 to 8. Summing
        fret deltas per string - asserted here for the contrast, because it is the metric this
        one is offered as a replacement for - sees three movements, having no way to know the
        two notes at fret 6 are one finger.
        """
        before = make_voicing([-1, -1, 6, 7, 6, -1])
        after = make_voicing([-1, -1, 7, 8, 7, -1])
        self.assertEqual(
            VoiceLeadingEngine.calculate_voice_leading_distance(before, after), 3.0
        )
        movement = finger_movement(
            assign_fingers(before), fingering_for([-1, -1, 7, 8, 7, -1])
        )
        self.assertEqual((movement.total, movement.largest), (2, 1))

    def test_all_four_fingers_shifting_one_fret_is_a_full_re_grip(self) -> None:
        """The mirror case of §1.1: four small per-string deltas are one hand movement.

        Every voice moves a semitone, which reads as a small change by per-voice measures and
        is a complete re-grip in fact. The total is 4 - one per finger - and `largest` is the
        smallest it can be for a change at all, so the pair describes "everything shuffled".
        """
        movement = finger_movement(
            fingering_for([-1, -1, 3, 4, 5, 6]), fingering_for([-1, -1, 4, 5, 6, 7])
        )
        self.assertEqual((movement.total, movement.largest), (4, 1))

    def test_a_leap_and_a_spread_are_ranked_oppositely_by_the_two_numbers(self) -> None:
        """§1.2: one finger leaping three frets is not three fingers moving two.

        From `5-6-7-8-x-x`: to `5-6-7-11-x-x` is one finger travelling three frets and totals
        3; to `5-6-9-10-x-x` is three fingers travelling two each and totals 4. The sum
        prefers the leap and `largest` prefers the spread, and a player would call the first
        the bigger move - so neither number alone describes both, which is why both are
        reported.
        """
        anchored = fingering_for([-1, -1, 5, 6, 7, 8])
        leap = finger_movement(anchored, fingering_for([-1, -1, 5, 6, 7, 11]))
        spread = finger_movement(anchored, fingering_for([-1, -1, 5, 6, 9, 10]))
        self.assertEqual((leap.total, leap.largest), (3, 3))
        self.assertEqual((spread.total, spread.largest), (4, 2))
        self.assertLess(leap.total, spread.total)
        self.assertGreater(leap.largest, spread.largest)

    def test_an_idle_finger_does_not_travel(self) -> None:
        """A lift is not movement: a two-finger shape moving a whole step totals 4, not 8.

        Measured from fret 0 instead, every unused finger would contribute how far up the neck
        the shape happens to be - a fact about the position rather than about the change.
        """
        movement = finger_movement(
            fingering_for([-1, -1, 3, 4, -1, -1]), fingering_for([-1, -1, 5, 6, -1, -1])
        )
        self.assertEqual((movement.total, movement.largest), (4, 2))

    def test_a_shape_does_not_move_from_itself(self) -> None:
        """The floor: the same shape twice is zero, whatever the shape is."""
        shape = fingering_for([-1, -1, 6, 7, 6, -1])
        movement = finger_movement(shape, shape)
        self.assertEqual((movement.total, movement.largest), (0, 0))

    def test_the_first_step_of_a_progression_has_not_moved(self) -> None:
        """`previous=None` is the call the first step makes, and nothing has moved yet."""
        movement = finger_movement(None, fingering_for([-1, -1, 3, 4, 5, -1]))
        self.assertEqual((movement.total, movement.largest), (0, 0))

    def test_a_substituted_finger_reads_as_no_movement_and_that_is_the_known_under_report(self) -> None:
        """The limitation the module's docstring admits, pinned so it cannot drift unseen.

        `x-x-3-4-5-x` -> `x-x-3-4-8-x`: the ring finger leaves fret 5 and the pinky arrives at
        8, which is what the score prefers to stretching the ring finger three frets. No
        finger travelled, so both numbers are 0 while the hand visibly moved. §5 step 2 is
        where this is weighed against real steps; until then this assertion is the record, and
        a test that inverted it would be claiming a fix nobody has made.
        """
        before = fingering_for([-1, -1, 3, 4, 5, -1])
        after = fingering_for([-1, -1, 3, 4, 8, -1])
        movement = finger_movement(before, after)
        self.assertEqual((movement.total, movement.largest), (0, 0))
        # It *is* a substitution rather than no change at all: the fingers differ.
        self.assertNotEqual(before.fingers, after.fingers)


class TestTheModuleIsInert(unittest.TestCase):
    """§4.1's claim - the module exists and nothing in the engine imports it - held to account.

    This is the test a step-3 change invalidates, and it must be **inverted rather than
    deleted** when that happens (AGENTS.md trap 5): at that point `cost`, `decisions` or
    `steps` will import `fingers`, and the useful assertion becomes "exactly these modules
    do, and here is what moved".
    """

    def test_nothing_in_the_engine_imports_it_yet(self) -> None:
        """No engine module imports `fingers`, so no existing output can have changed.

        Read from the AST rather than from `sys.modules`, for the reason
        `test_package_dag._imports_of` gives: a function-local import shows up here, which is
        exactly what should be caught, and it does not depend on what some other test happened
        to import first.
        """
        package = Path(arranger.__file__).parent
        importers = []
        for path in sorted(package.glob("*.py")):
            if path.stem in {"__init__", "fingers"}:
                continue
            for node in ast.walk(ast.parse(path.read_text())):
                if not isinstance(node, ast.ImportFrom):
                    continue
                names_fingers = node.module == "fingers" or any(
                    alias.name == "fingers" for alias in node.names
                )
                if names_fingers:
                    importers.append(path.stem)
        self.assertEqual(
            importers, [], "the engine imports fingers, so it is no longer inert"
        )

    def test_the_facade_binds_it_as_a_public_path(self) -> None:
        """`arranger.fingers` is reachable, and that binding is what the DAG check needs.

        `tests/test_package_dag.py::test_every_module_is_imported_by_something` counts
        `__init__` as an importer, so an inert engine module is reachable only through the
        facade - which is why the facade imports it while the engine does not, and why
        `"fingers"` is in `arranger.__all__`. The star-import surface is checked against the
        module's own namespace, so a bound public name missing from that list is a failure.
        """
        self.assertIs(arranger.fingers.assign_fingers, assign_fingers)
        self.assertIn("fingers", arranger.__all__)


if __name__ == "__main__":
    unittest.main()

